she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('story/<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('upload', views.ImageView.as_view(), name='image'),
    path('author/<int:auth>/', views.AuthorView, name='authorStory'),
    path('edit-story/<int:pk>/', views.EditStoryView.as_view(), name='editStory'),
    path('delete-story/<int:pk>/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('add-category/', views.AddCategoryView.as_view(), name='addCategory'),
    path('category/<str:cats>/', views.CategoryView, name='categoryStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
# the following are associated with uploading media files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/users/urls.py
from django.urls import path, include
from . import views
from .views import CreateAccountView
from .views import ChangeAccountView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('user-profile/', views.ProfileView.as_view(), name='userProfile'),
    path('upload', views.ImageView.as_view(), name='userImage'),
    path('edit-profile/', views.ChangeAccountView.as_view(), name='editProfile'),
]

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import ModelForm


FOUNDER = "Founder" 
PARTNER = "Partner"
MENTOR = "Mentor"
TEAM = "Team"
ADVOCATE = "Advocate"
FAMILY_TYPE = [
    (FOUNDER, "Founder"), 
    (PARTNER, "Partner"), 
    (MENTOR, "Mentor"),
    (TEAM, "Flair Team"), 
    (ADVOCATE, "Advocate")
]


class CustomUser(AbstractUser):
    # this is where I can put custom fields for a user - such as a profile image
    # the basics are included due to the 'AbstractUser' command
    first_name = models.CharField(max_length=30, verbose_name="first name")
    last_name = models.CharField(max_length=150, verbose_name="last name")
    business_name = models.CharField(max_length=100, verbose_name="business name", blank=True)
    type = models.CharField(max_length=20, verbose_name="family member type", choices=FAMILY_TYPE, default=FOUNDER)
    bio = models.TextField(verbose_name="tell us about yourself", blank=True)
    linkedin_url = models.CharField(max_length=200, verbose_name="linkedIn profile URL", default="Paste your LinkedIn URL here", blank=True)
    profile_photo = models.ImageField(upload_to='profile_photo/', verbose_name="profile photo", default="placeholder-1.jpg")

    @property
    def full_name(self):
        # "Returns the person's full name."
        return '%s %s' % (self.first_name, self.last_name)

    def __str__(self):
            return self.full_name


  

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    # to register/sign up as a new user
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'business_name', 'type', 'bio', 'linkedin_url', 'profile_photo']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.EmailInput(attrs={'class':'form-input', 'placeholder':'Enter email address', 'type':'email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'business_name': forms.TextInput(attrs={'class': 'form-input'}),
            'type': forms.Select(attrs={'class': 'form-imput', 'default': 'Founder'}),
            'bio': forms.Textarea(attrs={'class': 'form-input', 'placeholder': 'Tell us about you and your business'}),
            'linkedin_url': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Paste your LinkedIn URL here'}),
        }

class CustomUserChangeForm(UserChangeForm):
    # to make changes to an existing user
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'business_name', 'type', 'bio', 'linkedin_url', 'profile_photo']

she_codes_news/users/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from .models import CustomUser
from .forms import CustomUserCreationForm
from .forms import CustomUserChangeForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class ProfileView(generic.DetailView):
    model = CustomUser
    template_name = 'users/userProfile.html'
    context_object_name = 'profile'

    def get_object(self):
        return CustomUser.objects.all()

class ImageView(generic.CreateView):
    template_name = 'users/createAccount.html'

    def image_upload_view(request):
        """Process images uploaded by users"""
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                # Get the current instance object to display in the template
                img_obj = profile.image
                return render(request, 'userProfile.html', {'form': form, 'img_obj': img_obj})
        else:
            form = CustomUserCreationForm()
        return render(request, 'createAccount.html', {'form': form})

class ChangeAccountView(UpdateView):
    form_class = CustomUserChangeForm
    success_url = reverse_lazy('users:userProfile')
    template_name = 'users/editProfile.html'
    
    def get_object(self):
        return self.request.user

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}
{% block title %}FFN: Create An Account{% endblock %}

{% block content %}
<div class="account-page">
    <h2>Create an Account</h2>
    <p>To be able to publish stories, you will need to create an account and set up your profile.
        If you already have a profile, please <a href="{% url 'login' %}">login</a> instead.
    </p>
</div>

<div class="new-form">
    <form action ="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-fields">
            {{ form.as_p }}
        <button type="submit">Create Account</button>
        </div>
    </form>
</div>

{% endblock %}

she_codes_news/users/templates/users/editProfile.html
{% extends 'base.html' %}
{% block title %}FFN: Edit Your Account{% endblock %}

{% block content %}

<div class="account-page">
    <h2>Edit Your Profile</h2>
    <p>Keep your profile up to date, so that anyone who wants to connect with you can do so easily.
        If you already have a profile, please <a href="{% url 'login' %}">login</a> instead.
    </p>
</div>

{% if request.user.is_authenticated %}
<div class="new-form">
    <form action ="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-fields">
            {{ form.as_p }}
        <button type="submit" id="form-button">Edit Account</button>
        </div>
    </form>
</div>
{% endif %}
{% endblock %}

she_codes_news/users/templates/users/userProfile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}FFN: Profile of {{ user.full_name }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}">
{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}

<div class="account-page">
    <div class="user-intro">
        <h3>Welcome Home {{ user.first_name }}</h3>
        <p>Your profile details are visible to readers of The Flair Family News.</p>
        <p>If you need to update your details, you can <a href="{% url 'users:editProfile' %}">edit</a> them.</p>
        <p>Are you ready to publish a <a href="{% url 'news:newStory' %}">new story</a>?</p>
        <p></p>
    </div>

    <div class="profile">
        <h3>Your Profile Details</h3>
        <div id="profile-photo">
            <p>Profile Photo: </p>
            <img src="{{ user.profile_photo.url }}" alt="" width="250" alt="{{ user.first_name }} Profile Photo">
        </div>
        <div class="profile-details">
            <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
            <p>Business Name: {{ user.business_name }}</p>
            <p>Flair Family: {{ user.type }}</p>
            <p>Your Story: {{ user.bio|linebreaks }}</p>
            <p>LinkedIn URL: {{ user.linkedin_url }}</p>
        </div>
    </div>

    <div class="profile">
        <h3>Your Private Information</h3>
        <div class="profile-details">
            <p>Username: {{ user.username }}</p>
            <p>Email: {{ user.email }}</p>
        </div>
    </div>
</div>

{% else %}
<div class="account-page">
    <h2>No Profile Details Available</h2>
    <p>To view your profile details, please<a href="{% url 'login' %}"> login</a>.</p>
</div>
{% endif %}

{% endblock %}