she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('story/<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('upload', views.ImageView.as_view(), name='image'),
    path('author/<int:auth>/', views.AuthorView, name='authorStory'),
    path('edit-story/<int:pk>/', views.EditStoryView.as_view(), name='editStory'),
    path('delete-story/<int:pk>/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('add-category/', views.AddCategoryView.as_view(), name='addCategory'),
    path('category/<str:cats>/', views.CategoryView, name='categoryStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
# the following are associated with uploading media files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/users/urls.py
from django.urls import path, include
from . import views
from .views import CreateAccountView
from .views import ChangeAccountView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('user-profile/', views.ProfileView.as_view(), name='userProfile'),
    path('upload', views.ImageView.as_view(), name='userImage'),
    path('edit-profile/', views.ChangeAccountView.as_view(), name='editProfile'),
]

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
                The Flair Family News
            {% endblock %}
        </title>
        <meta name="description" content="">
        <meta name="author" content="Joy Taylor">
        <link href="https://fonts.googleapis.com/css2?family=Playball&family=Quicksand&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>
    
    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>The Flair Family News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a href="{% url 'users:userProfile' %}">{{ request.user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
        <div class="nav-views">
           
        </div>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:createAccount' %}">Register</a>
    {% endif %}
</nav>