she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('story/<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('upload', views.ImageView.as_view(), name='image'),
    path('author/<int:auth>/', views.AuthorView, name='authorStory'),
    path('edit-story/<int:pk>/', views.EditStoryView.as_view(), name='editStory'),
    path('delete-story/<int:pk>/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('add-category/', views.AddCategoryView.as_view(), name='addCategory'),
    path('category/<str:cats>/', views.CategoryView, name='categoryStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
# the following are associated with uploading media files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.forms import ModelForm
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="category")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('index')


class NewsStory(models.Model):
    # created_at = models.DateTimeField(auto_now_add=True, story_name="Created at")
    # updated_at = models.DateTimeField(auto_now=True, story_name="Updated at")
    title = models.CharField(max_length=100, verbose_name="story title")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    pub_date = models.DateTimeField(verbose_name="date published")
    category = models.CharField(max_length=20, verbose_name="story category", default='Type of Story')
    content = models.TextField(verbose_name="")
    image = models.ImageField(upload_to='story_image/', verbose_name="story photo", default="placeholder-1.jpg")
    @property
    def better_date(self):
        if self.pub_date:
            return self.pub_date.strftime("%d %b %Y")
        else:
            return "no_date"

    def get_absolute_url(self):
        return reverse('index')

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, Category
from users.models import CustomUser

choices = Category.objects.all().values_list('name', 'name')

choice_list = []

for item in choices:
    choice_list.append(item)


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'category', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'pub_date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-input', 'placeholder':'Select a date', 'type':'date'}),
            'content': forms.Textarea(attrs={'class': 'form-input', 'placeholder': 'Write the story here'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-input'}),
        }

class SelectAuthorForm(forms.Form):
    class Meta:
        author = forms.ModelChoiceField(queryset=CustomUser.objects.all())

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from .models import NewsStory, Category
from .forms import StoryForm
from .forms import SelectAuthorForm
from users.models import CustomUser
from django.http import HttpResponseNotFound

class IndexView(generic.ListView):
    form_class = SelectAuthorForm
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date').all()[:3]
        context['all_stories'] = NewsStory.objects.order_by('-pub_date').all()
        return context

class ImageView(generic.CreateView):
    template_name = 'news/createStory.html'

    def image_upload_view(request):
        """Process images uploaded by users"""
        if request.method == 'POST':
            form = StoryForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                # Get the current instance object to display in the template
                img_obj = story.image
                return render(request, 'story.html', {'form': form, 'img_obj': img_obj})
        else:
            form = StoryForm()
        return render(request, 'createStory.html', {'form': form})

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class EditStoryView(generic.UpdateView):
    model = NewsStory
    form_class = StoryForm
    template_name = 'news/editStory.html'
    success_url = reverse_lazy('news:index')

class DeleteStoryView(generic.DeleteView):
    model = NewsStory
    template_name = 'news/deleteStory.html'
    success_url = reverse_lazy('news:index')
    
def AuthorView(request, auth):
    # auth = request.user
    auth_story = NewsStory.objects.filter(author=auth)
    return render(request, 'news/storyby.html', {'auth':auth, 'auth_story':auth_story})

class AddCategoryView(generic.CreateView):
    model = Category
    template_name = 'news/addCategory.html'
    fields = '__all__'
    success_url = reverse_lazy('news:index')

def CategoryView(request, cats):
    category_story = NewsStory.objects.filter(category=cats)
    return render(request, 'news/category.html', {'cats': cats, 'category_story':category_story})

she_codes_news/news/templates/news/addCategory.html
{% extends "base.html" %}
{% block title %}FFN: Add a new category{% endblock %}

{% block content %}
<div class="new-story-page">
    <h3>Add a Category</h3>
    <p>Create a new Category of story.</p> 
</div>

<div class="new-form">
    <form action ="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-fields">
            {{ form.as_p }}
        <button type="submit" id="form-button">Add Category</button>
        </div>
    </form>
</div>

{% endblock %}

she_codes_news/news/templates/news/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}FFN: Stories about {{ cats }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<h2>Stories about {{ cats }}</h2>

{% for story in category_story %}
    <div class="story-card" id="story-card-{{ position }}">
        <img src="{{ story.image.url }}" alt="" width="250">
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4><a href="{% url 'news:authorStory' story.author.id %}">{{ story.author.full_name }}</a> | {{ story.better_date }}</h4>
            {{ story.content|slice:"150" }} <a href="{% url 'news:story' story.id %}">read more...</a>
        </div>
    </div>

{% endfor %}



{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}
<div class="new-story-page">
    <h3>Submit your story</h3>
    <p>Enter all of the details relevant to your story in the fields below.</p> 
    <p>Your article will be immediately published on The Flair Family News - Home Page.</p>
</div>

<div class="new-form">
    <form action ="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-fields">
            {{ form.as_p }}
        <p>Recommended Image: .jpg file, 1980x1080px, max 100kb</p>
        <button type="submit" id="form-button">Submit your story</button>
        </div>
    </form>
</div>

{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}
{% load static %}
{% block title %}FFN: Delete story{% endblock %}

{% block content %}
<div class="new-story-page">
    <h3>Delete your story</h3>
    <p>If your story is no longer accurate and is no longer needed, it can be deleted.</p> 
    <p>Once you delete your story, it will immediately be remove from The Flair Family News is cannot be recovered.</p>
    <br>
    {% if request.user.is_authenticated %}
    <h3>Delete: {{ story.title }} by {{ story.author.full_name }}</h3>
</div>

<div class="new-form">
    <form action ="" method="post">
        {% csrf_token %}
        <div class="form-fields">
            <p><strong>Are you sure you want to delete?</strong></p>
        <button type="submit" id="form-button">Delete story</button>
        </div>
    </form>
</div>
{% endif %}

{% endblock %}

she_codes_news/news/templates/news/editStory.html
{% extends "base.html" %}
{% block title %}FFN: Edit story{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<div class="new-story-page">
    <h3>Edit your story</h3>
    <p>Edit any of the details to your story in the fields below.</p> 
    <p>Your article will be immediately re-published on The Flair Family News - Home Page.</p>
</div>

<div class="new-form">
    <form action ="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-fields">
            {{ form.as_p }}
        <p>Recommended Image: .jpg file, 1980x1080px, max 100kb</p>
        <button type="submit" id="form-button">Edit your story</button>
        </div>
    </form>
</div>
{% else %}

<p>To edit a story, please <a href="{% url 'login' %}">login</a> first</p>

{% endif %}

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<p>Welcome to the Flair Family News!</p>
<p>Here you will find stories about the wonderful female-led businesses that aspire to grow into an international market.
    <br>All of the founders reside in Regional Queensland, and took part in a 16-week Incubator program from August to December 2020.</p>
<p>The Flair Incubator was delivered by the team from Canvas Coworking, in Toowoomba, Queensland.</p>
<p>The program received funding support from the Australian Government.</p>
<br><br>
{% if request.user.is_authenticated %}
<p>Welcome back {{user.first_name }}</p>
<p>Are you ready to publish a <a href="{% url 'news:newStory' %}">new story</a>?</p>
<p>Would you like to create a <a href="{% url 'news:addCategory' %}">new Story Category</a>?</p>
{% endif %}

<h2>Latest Stories</h2>
    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <br><br>
<h2>All Stories</h2>
    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}
{% block title %}FFN: {{ story.title }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>by {{ story.author.full_name }}</h4>
    <h4>{{ story.category }}</h4>
    <div id="story-content">
        <img src="{{ story.image.url }}" alt="" width="250">
        {{ story.content|linebreaks }}
    </div>
</div>
<br>
<br>
<p>Return to the <a href="{% url 'news:index' %}">Latest News Page</a></p>

{% if request.user.is_authenticated %}
<h4>Does this story need an update?</h4>
<p><a href="{% url 'news:editStory' story.pk %}">Edit this story</a></p>

<h4>Do you want to delete this story?</h4>
<p><a href="{% url 'news:deleteStory' story.pk %}">Delete this story</a></p>
{% endif %}

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}


<div class="story-card" id="story-card-{{ position }}">
        <img src="{{ story.image.url }}" alt="" width="250">
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4><a href="{% url 'news:authorStory' story.author.id %}">{{ story.author.full_name }}</a> | {{ story.better_date }} | 
                <a href="{% url 'news:categoryStory' story.category %}">{{ story.category }}</a></h4>
            {{ story.content|slice:"150" }} <a href="{% url 'news:story' story.id %}">read more...</a>
        </div>
</div>

she_codes_news/news/templates/news/storyby.html
{% extends "base.html" %}
{% load static %}
{% block title %}FFN: Stories by {{ user.full_name }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

{% for story in auth_story %}
<h2>Stories by {{ story.author.full_name }} </h2>

    <div class="author-stories" id="author-story-card">
        <img src="{{ story.image.url }}" alt="" width="250">
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.better_date }} | 
                <a href="{% url 'news:categoryStory' story.category %}">{{ story.category }}</a></h4>
            {{ story.content|slice:"150" }} <a href="{% url 'news:story' story.id %}">read more...</a>
        </div>
    </div>

{% endfor %}

{% endblock %}